-- Create hero_section table
CREATE TABLE IF NOT EXISTS hero_section (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  subtitle TEXT,
  image_url VARCHAR(500),
  image_alt VARCHAR(255),
  cta_text VARCHAR(100),
  cta_url VARCHAR(500),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE hero_section ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON hero_section
  FOR SELECT USING (is_active = true);


-- Create promo_section table
create table promo_section (
  id bigint generated by default as identity primary key,
  timeline varchar(100) not null,
  jenis_promo text not null,
  is_promo boolean default false,
  created_at timestamp with time zone default now()
);

ALTER TABLE promo_section ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON promo_section
  FOR SELECT
  USING (is_promo = true);
