-- Create hero_section table
CREATE TABLE IF NOT EXISTS hero_section (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  subtitle TEXT,
  image_url VARCHAR(500),
  image_alt VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE hero_section ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON hero_section
  FOR SELECT USING (is_active = true);

-- Create promo_section table
create table promo_section (
  id bigint generated by default as identity primary key,
  timeline varchar(100) not null,
  jenis_promo text not null,
  is_promo boolean default false,
  created_at timestamp with time zone default now()
);

ALTER TABLE promo_section ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON promo_section
  FOR SELECT
  USING (is_promo = true);

-- Create visi_misi table
CREATE TABLE visi_misi (
  id SERIAL PRIMARY KEY,
  visi TEXT,
  misi_1 TEXT,
  misi_2 TEXT,
  misi_3 TEXT,
  misi_4 TEXT,
  misi_5 TEXT
);

-- Create berita table
create table berita (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  slug text unique not null,
  hero_url text, -- gambar hero
  excerpt text, -- deskripsi singkat
  content text not null, -- isi artikel markdown
  created_at timestamp default now()
);
